"""empty message

Revision ID: d397e23ee861
Revises: 6efae7b1c2f5
Create Date: 2020-07-21 00:53:57.195159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd397e23ee861'
down_revision = '6efae7b1c2f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.execute('UPDATE "Venue" SET seeking_talent=False WHERE seeking_description IS NULL')
    op.alter_column('Venue','seeking_talent',nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###
